version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GID: 502
        UID: 80
        github_token: 21e6ada93646c30cab8243a78883751457e10a80
    hostname: coukraine.loc
    volumes:
      - "./:/var/www/coukraine"
    tty: true
    depends_on:
      - db
    network_mode: host

  db:
    build:
      context: ./docker/db
      args:
        GID: 502
        UID: 80
    restart: always
    volumes:
      - "./docker/.data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
    ports:
      - "3306:3306"
    expose:
      - 3306

  nginx:
    build:
      context: ./docker/nginx
      args:
        GID: 502
        UID: 80
    depends_on:
      - app
    volumes:
      - "./:/var/www/coukraine"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    expose:
      - 80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=vagrant