version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - "../:/var/www/coukraine"
    tty: true
    depends_on:
      - db
    network_mode: host

  db:
    image: mariadb:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306

  nginx:
    build: nginx
    depends_on:
      - app
    volumes:
      - "../:/var/www/coukraine"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    expose:
      - 80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
